### ISSUE TITLE
Option floyd:1 causes an error.

### ISSUE THREAD

**Issue by message** [imagemin/imagemin-pngquant#11]
Actually it's every value except for 0
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error:   error: cannot open - for reading

    at Socket.<anonymous> (/Users/message/www/jsapp/node_modules/imagemin-pngquant/index.js:59:14)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)
```

**Comment by liviubunda** [comment]
+1

**Comment by liviubunda** [comment]
Found the problem, should be --floyd=0.1, not --floyd 0.1 as it is implemented right now. 

Also, --verbose causes some output on stderr (since stdout is being used for the new image) and the code stops when there is something written to stderr.

I'll make a fork and submit a pull request.

**Comment by kevva** [comment]
@pornel, is this intended? One would assume that a space after long flags with the value would work.

**Comment by pornel** [comment]
Yes, it's intended because `--floyd` is also a boolean flag (i.e. `pngquant --floyd file.png` works)

**Comment by kevva** [comment]
:+1:, we should take that into account somehow.

**Comment by kevva** [comment]
Fixed in https://github.com/imagemin/imagemin-pngquant/commit/86c8b9aa10fba6f3a9d6830a6da21cf89b9391dc.
