### ISSUE TITLE
CentOS 6: GLIBC_2.14 not found

### ISSUE THREAD

**Issue by magic890** [imagemin/imagemin-pngquant#12]
I'm using this plugin via Gulp (i.e. via Node), and I'm getting this error on CentOS 6:

    /node_modules/imagemin-pngquant/node_modules/pngquant-bin/vendor/pngquant: /lib64/libc.so.6: version `GLIBC_2.14' not found

It works fine under Mac OS X but not in CentOS.

**Comment by kevva** [comment]
That's because the binary is compiled using a newer version of libc. Does it proceed to build the binaries for you?

**Comment by magic890** [comment]
I run:

    yum install libpng-devel.x86_64
    npm update

and the build pass.

Now I'm trying to run `gulp` but I'm getting this error:

    events.js:72
        throw er; // Unhandled 'error' event
              ^
    Error: write EPIPE
        at errnoException (net.js:905:11)
        at Object.afterWrite (net.js:721:19)

Here is the Gulp task:

    ...
    var imagemin = require('gulp-imagemin');
    gulp.task('images', function() {
        return gulp.src(PATH.SRC_DIR + PATH.SRC.IMG + '**')
            .pipe(imagemin({
                progressive: true,
                svgoPlugins: [{removeViewBox: false}],
                use: [pngquant()]
            }))
            .pipe(gulp.dest(PATH.DEST_DIR + PATH.DEST.IMG));
    });
    ...

**Comment by kevva** [comment]
Hm, try remove the `node_modules` folder and install again.

**Comment by nervo** [comment]
@kevva, yep, i will build one.
@magic890 could you just tell us which version of centos do you use, 32 or 64 bits, and the version of glibc provided in it ?

**Comment by magic890** [comment]
@nervo I'm using `CentOS release 6.6 (Final) x64` with kernel `2.6.32-504.16.2.el6.x86_64`
@kevva unfortunately reinstalling node modules not solved this issue, I'm getting this warning:

    ⚠ The `/usr/share/nginx/html/summarization-frontend/node_modules/imagemin-pngquant/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
      ⚠ pngquant pre-build test failed
      ℹ compiling from source
      ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
        at ChildProcess.exithandler (child_process.js:658:15)
        at ChildProcess.emit (events.js:98:17)
        at maybeClose (child_process.js:766:16)
        at Socket.<anonymous> (child_process.js:979:11)
        at Socket.emit (events.js:95:17)
        at Pipe.close (net.js:466:12)

and Gulp fails:

    events.js:72
        throw er; // Unhandled 'error' event
              ^
    Error: write EPIPE
        at errnoException (net.js:905:11)
        at Object.afterWrite (net.js:721:19)

**Comment by nervo** [comment]
@magic890 and what about the glibc version ?

(also, when you read "make sure that libpng-dev is installed", maybe you should try to install it :) Something like "yum install libpng-devel", i guess)

**Comment by magic890** [comment]
@nervo glibc:

    Package glibc-2.12-1.149.el6_6.9.x86_64 already installed and latest version
    Package glibc-common-2.12-1.149.el6_6.9.x86_64 already installed and latest version

I've also installed the devel version:

    Installed:
      glibc-devel.x86_64 0:2.12-1.149.el6_6.9

    Dependency Installed:
      glibc-headers.x86_64 0:2.12-1.149.el6_6.9
      kernel-headers.x86_64 0:2.6.32-504.30.3.el6

Regarding `libpng-devel` it is already installed as mentioned above:

> yum install libpng-devel.x86_64

**Comment by nervo** [comment]
Ouch' ! 2.12 !
CentOS is more outdated than Debian :)
I can not provide a binary for this, i guess you have to build it manually...

(sorry for libpng-devel, i did'nt read well your mentions)

**Comment by mcblum** [comment]
Did anyone every figure this out? It's causing me tons of errors as well.

**Comment by shinnn** [comment]
Just upgrade CentOS.

**Comment by Ark2** [comment]
Navigate to `\node_modules\<package>\dist` and Paste all the required Libraries there that will keep you safe from bricking your system

**Comment by nervo** [comment]
@abeersaqib you must be joking, ah ah :)

**Comment by Rolice** [comment]
I had a similar issue with CentOS 7. The binary file in the package is somehow incompatible with the Linux image (CentOS 7 latest). I have described my solution here: https://stackoverflow.com/questions/29930978/node-js-imagemin-on-centos/45567290#45567290.
