### ISSUE TITLE
verbose parameter causes imagemin to stop with error

### ISSUE THREAD

**Issue by liviubunda** [imagemin/imagemin-pngquant#14]
The --verbose parameter causes some output on stderr (since stdout is being used for the new image) and the code stops when there is something written to stderr.

This should be handled a bit differently. If the verbose flag is present, the stderr data chunks should be concatenated and pushed to some sort of logging mechanism.

I would do this myself, but I'm unfamiliar with how the logging should be done in this case.

**Comment by sindresorhus** [comment]
Fixed in 4.2.1.
