### ISSUE TITLE
floyd argument must be in 0..1 range

### ISSUE THREAD

**Issue by ArcherZkd** [imagemin/imagemin-pngquant#15]
when i  set floyd  find the argument has a range？

but i use the pngquant cli directly，and set some num is ok  why？

here is use imagemin-pngquant
![image](https://cloud.githubusercontent.com/assets/1777132/8890223/95deb26c-332a-11e5-86a2-529a908b0c32.png)

![image](https://cloud.githubusercontent.com/assets/1777132/8890206/0f9663b2-332a-11e5-8c71-bdf762114e93.png)

here is use cli directly
![image](https://cloud.githubusercontent.com/assets/1777132/8890217/7971270e-332a-11e5-8599-a73a66a0fc39.png)

**Comment by shinnn** [comment]
1. Which version of `imagemin-pngquant` are you using?
2. Which version of `pngquant` CLI are you using?
