### ISSUE TITLE
4.2 seems very slow

### ISSUE THREAD

**Issue by emlyn-Resn** [imagemin/imagemin-pngquant#16]
I just updated from 4.1 to 4.2, and my optimization time has jumped about 10-fold.

Running via grunt-contrib-imagemin, and processing a lot of fairly large (2048x2048), images, using the following settings:

`pngquant({ quality: '65-80', speed: 4 })`

Reverting back to 4.1 seems to restore the performance.

Happening on Windows 10/7 and OSX.

**Comment by shinnn** [comment]
https://github.com/rvagg/through2
