### ISSUE TITLE
Cannot find module imagemin

### ISSUE THREAD

**Issue by fernandofas** [imagemin/imagemin-pngquant#27]
Hi there,

I have installed imagemin and imagemin-pngquant on my project and when I run "gulp" the following message come sup on the cmd:

module.js 327
throw err;
^

Error: Cannot find module 'imagemin
at Function.Module._resolveFilename  <module.js:325:15>
at Function.Module._load <module.js:353:17>
at Module.require <module.js:353:17>
at require <internal/module.js:12:17>
at Object.<anonymous> <C:\User\user\Desktop\test7\guulfile.js:10:16>
at Module._compile <module.js:409:26>
at Object.Module._extensions..js <module.js:416:10>
at Module.load <module.js:343:32>
at Function.Module._load <module.js:300:12>
at Module.require <module.js:353:17>

So, my gulpfile.js is configurate as follow:

var gulp = require('gulp'),
    jade = require ('gulp-jade');
    data = require('gulp-data');
    swig = require('gulp-swig');
    sass = require('gulp-sass');
    copy = require('gulp-contrib-copy');
    uglify = require('gulp-uglify');
    rename = require('gulp-rename');
    compressor = require('gulp-compressor');  
    imagemin = require('imagemin');
    imageminPngquant = require('imagemin-pngquant');
    mozjpeg = require('mozjpeg');

// optimize images
gulp.task('imagemin', () => {
	return gulp.src('templates/img/*')
		.pipe(imagemin({
			progressive: true,
			svgoPlugins: [{removeViewBox: false}],
			use: [ mozjpeg(), pngquant( {
            quality: '20-70',
            speed: 1
          } ) ]
		}))
		.pipe(gulp.dest('builds/development/img/'));
});

imagemin(['templates/img/*.png'], 'builds/development/img/', {use: [imageminPngquant()]}).then(() => {
	console.log('Images optimized');
});

........

gulp.task('default', ['templates', 'copy', 'compress', 'sass', 'css', 'html', 'copy1', 'imagemin'], function(){});

Is there any instructions missing on the npm page of the plugin or any missing config on my gulpfile.js?

Any help it will be great.

Kind regards,

Fernando Fas

**Comment by kevva** [comment]
You should use https://github.com/sindresorhus/gulp-imagemin with gulp :).
