### ISSUE TITLE
Getting an error image quality < plugins' options

### ISSUE THREAD

**Issue by YoannMa** [imagemin/imagemin-pngquant#30]
Hello,

I'm using pngquant before uploading a file and when i use a file with a quality inferior of the pngquant options, i got an error `Command failed`

I used the verbose mode to see what's causing the error and i got 

`image degradation MSE=4.988 (Q=83) exceeded limit of 4.482 (85)`

So i was thinking, is this normal, should it avoid throwing an error and ignore it?
```javascript
_compress : (context) => {
        return new Promise((fulfill, reject)=> {
            if (/^image\/(jpg|jpeg|png)$/.test(context.type)) {
                Imagemin.buffer(context.data, {
                    plugins : [
                        mozjpeg({
                            progressive : true,
                            quality     : 70,
                            quantTable  : 2
                        }),
                        pngquant({
                            quality : '85-100',
                            speed   : 3
                        })
                    ]
                }).then(buffer => {
                    context.data = buffer;
                    fulfill(context)
                }).catch(reject);
            } else {
                fulfill(context);
            }
        })
    }
```

**Comment by leachiM2k** [comment]
Hello,

we ran into the same problem just yesterday. Yes, I know, this is a normal behavior of pngquant itself, but it is very confusing to get that "error" and having the imagemin chain breaking.
It would be very cool to see a solution or a work around.

**Comment by narf** [comment]
I encountered this error too.
To me the lib is just a way to optimize images the best it can. If an optimization is not possible it should output at least the original version with a warning.

Crashing like it does do not offer us any way to fix the quality problem, we do not know which file crash nor we can programatically skip the optimization for this file. It is a real pain.

Except for this problem, the lib is a good tool, thanks for the work.

**Comment by kevva** [comment]
Why don't you lower your `quality` option? You're explicitly telling `pngquant` to not allow images have a quality below this.

**Comment by YoannMa** [comment]
It's true that I can lower the `quality` but my use case is to have a max quality at 85% and getting an image with a lower quality don't bother me.

If there were a way to get the actual quality, I could check before processing the image and everything is OK.

**Comment by kevva** [comment]
You have a minimum quality of `85%` and maximum of `100%`.

**Comment by YoannMa** [comment]
Oh my bad, i didn't understand the doc in that way

So if I use 85% as maximum quality and I put an image with a quality superior at 85%, it'll be compressed to 85% ?

**Comment by kevva** [comment]
If it can, yes.

**Comment by YoannMa** [comment]
I'll try that so, thanks for the help.

**Comment by kevva** [comment]
If you aren't concerned about having a minimum quality, just remove the option altogether.
