### ISSUE TITLE
(issue with upstream/pngquant bin?) Process exits with error

### ISSUE THREAD

**Issue by strarsis** [imagemin/imagemin-pngquant#32]
PNG images outputted from node sharp are piped into pngquant for lossy and advanced optimisations.

An error occurs when the quality string for pngquant contains a too narrow range (e.g. '80-90'):
````
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Command failed: /home/user/test/node_modules/pngquant-bin/vendor/pngquant --output /tmp/06882c02-6fe8-41d9-b706-3e8ab3eb2f17 /tmp/13322606-798c-4f90-b540-e384134c9280 --quality 90-100 --speed 3

    at /home/user/test/node_modules/execa/index.js:170:11
    at process._tickCallback (node.js:385:9)
[...]
````
Gulp and the node process completely exits prematurely.

Edit: According to caught error, pngquant binary exited with code 99, which is described here: https://github.com/pornel/pngquant#--quality-min-max
This module should handle the error, emit an info or warning but not fail like it does currently.

**Comment by shinnn** [comment]
Thanks for the report, @strarsis. Do you have interest in submitting a pull request? Maybe checking the exit code in [L54-L57](https://github.com/imagemin/imagemin-pngquant/blob/ba94afa05bc7a152ec8022b4d18a1eb45e15c241/index.js#L54-L57) like https://github.com/imagemin/imagemin-pngquant/commit/213b0934a39d2711df5333d03148a83b1204d292 solves the problem.
