### ISSUE TITLE
Minify fails because of a specific png 24bit image

### ISSUE THREAD

**Issue by lexbi** [imagemin/imagemin-pngquant#37]
I've seen this specific error on a few threads already, but, their fixes don't seem to help. 

It seems to have a problem with a specific 24bit png file (3 other 24bit png files minify ok), if I remove the png, or, make the same png 8bit, it minifies ok.

I have just installed an xcode update, so many that has effected it somehow?

I have tried: 
restarting macos, 
restarting terminal, 
deleting `node_modules` then `npm install` again
I noticed imagemin-pngquant uses pngquant-bin 3.0.0 so i tried getting the latest with `npm install --save-dev pngquant-bin` though this doesn't work either, same error comes back.

Have you any suggestions?

Here is the error:

    events.js:160
          throw er; // Unhandled 'error' event
          ^
    Error: Command failed: /Users/username/sites/site/node_modules/pngquant-bin/vendor/pngquant --output /var/folders/b5/qlvcks2d5j7c3l136tl9646m0000gn/T/cb38ae47-2d2c-4380-8bda-c4bf3eacfd13 /var/folders/b5/qlvcks2d5j7c3l136tl9646m0000gn/T/12c612f5-6612-4775-b4e4-829c6329b6a6 --quality 75-85

        at Promise.all.then.arr (/Users/username/sites/site/node_modules/execa/index.js:201:11)
        at process._tickCallback (internal/process/next_tick.js:103:7)

System details:
macOS 10.12.4
node v6.8.0
gulp cli 1.2.1
gulp local 3.9.1

**Comment by Zephir77167** [comment]
Was fixed by https://github.com/imagemin/imagemin-pngquant/pull/33 and now we are waiting for a version bump!
