### ISSUE TITLE
tunneling socket could not be established, statusCode=403

### ISSUE THREAD

**Issue by LittleHendrix** [imagemin/imagemin-pngquant#41]
Hi there,
I'm having some issues installing this module from behind a proxy. I've followed some online examples and set up my .npmrc to include the http and https proxy settings:

```
proxy=http://myproxy:port/
https-proxy=http://myproxy:port/
strict-ssl=false
ca=null
registry=http://registry.npmjs.org/
```
but I'm still getting the error when npm gets to the **node lib/install.js** stage.
Also, I have environment variable set up for HTTP_PROXY and HTTPS_PROXY on my machine too. 

My setup is as follows:
OS: Windows 7 enterprise 64bit
NODE: v6.11.3
NPM: v3.10.10

I have no issues with this at home (no proxy).
Will you be able to help please?

**Comment by sindresorhus** [comment]
Closing as this looks unrelated to this package and it's very old.
