### ISSUE TITLE
Image not optimizing

### ISSUE THREAD

**Issue by asafigan** [imagemin/imagemin-pngquant#42]
I have an image that is not optimizing. I tried using pngquant directly and it optimized the image no problem.
![thumb_1501621736](https://user-images.githubusercontent.com/18042227/31090025-2964fd1a-a774-11e7-8b9c-cc06d86a63b0.png)

**Comment by asafigan** [comment]
Found the issue. Your code is not throwing the 99 error. Can there be a better explanation on what the quality option does? I don't understand completely. Is it an important option or should I not use it?

**Comment by asafigan** [comment]
Reading the readme more closely, I think this option adds an additional optimization, but checks the quality of that optimization. Is this true?

**Comment by kevva** [comment]
What options did you run it with? When optimizing it on `macOS` I get an 20 KB image as opposed to 170 KB which the source image is.

**Comment by asafigan** [comment]
the problem was that I added quality '70-80'. I didn't really know what quality did at the time. I decided to leave the option out and it works fine. Would still like a better explanation of this option

**Comment by kevva** [comment]
The `quality` option is a "threshold", sort of. You define a range in which the image can't be under the minimum. Maybe `70-100` would've worked better, or even lowering the minimum a bit.

**Comment by asafigan** [comment]
I left this out because it seems to add another level of optimization that isn't needed.
