### ISSUE TITLE
Does not support node7.0 +

### ISSUE THREAD

**Issue by sbfkcel** [imagemin/imagemin-pngquant#43]
The installation is prompted to depend on the components do not support node7.0 +

WARN node unsupported "node@v7.10.0" is incompatible with imagemin-pngquant@5.0.1 › pngquant-bin@3.1.1 › bin-build@2.2.0 › download@4.4.3 › got@^5.0.0, expected node@>=0.10.0 <7

There are already new versions of the components that need to be dependent. Can I update it?

Thank you.

**Comment by cvillanujr** [comment]
I'm on the same boat, trying to install it but stops because it's checking for node <7. I'm running 8.10.0 and downgrading is not an option.
