### ISSUE TITLE
How to use it？

### ISSUE THREAD

**Issue by cooper1x** [imagemin/imagemin-pngquant#53]
For example, I have a lot of png files in a folder. How do I set the input directory and output directory?

**Comment by mell0kat** [comment]
I had the same question ^. How can we specify output folder structure?  If input looks like this `static/img/**/*.gif`, how can we tell the plugin to match the same recursive structure on the output?

**Comment by 1000ch** [comment]
Details to see [imagemin#usage](https://github.com/imagemin/imagemin#usage).
