### ISSUE TITLE
Error with gulp

### ISSUE THREAD

**Issue by rafu1987** [imagemin/imagemin-pngquant#56]
I'm getting the following error, when using with gulp-imagemin:

`{ ArgumentError: Expected argument to be of type 'array' but received type 'number'`

My gulp config:

```
      $.imagemin(
        [
          imageminPngquant({
            quality: 75
          })
        ],
        {
          plugins: [
            imageminPngquant
          ],
          verbose: true
        }
      )
```

gulp 4.0.0
gulp-imagemin 5.0.3
imagemin-pngquant 7.0.0

**Comment by Transoman** [comment]
I also have this error.

gulp 4.0.0
gulp-imagemin 5.0.3
imagemin-pngquant 7.0.0

Installed version 6.0.1 the error was gone.

**Comment by maximedaoust** [comment]
imagemin-pngquant changed the quality option. 
The quality option now expect an array with two values between 0 and 1. 
Here is an example `quality: [0.7, 0.8]`

**Comment by rafu1987** [comment]
Hey @maximedaoust - thanks for the hint! Works now for me :-)
