### ISSUE TITLE
Unable to process images larger than 10MB

### ISSUE THREAD

**Issue by TitanNano** [imagemin/imagemin-pngquant#60]
This package depends on `execa` which sets the `maxBuffer` option by default to 10 MB, unfortunately that causes this package to fail at processing images larger than 10 MB. 
Please raise the maximum to `Infinity` so any image can be processed.

**Comment by sindresorhus** [comment]
This is already the case: https://github.com/imagemin/imagemin-pngquant/blob/6ce8a90eac53b57fc106a2afc7dc6c0fd102399b/index.js#L59
