### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by tiger-BeA** [imagemin/imagemin-pngquant#65]
When I use yarn to install imagemin-pngquant, has error like this. 
But I have executed `brew install libpng` yet.

`Command: node lib/install.js
Arguments: 
Directory: /Users/lisw/Downloads/JOB/conan-episode-optimize/node_modules/pngquant-bin
Output:
⚠ connect ECONNREFUSED 0.0.0.0:443
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng is installed
    at /Users/lisw/Downloads/JOB/conan-episode-optimize/node_modules/bin-build/node_modules/execa/index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
`

**Comment by cyzaoj** [comment]
+1
