### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by davetgreen** [imagemin/imagemin-pngquant#9]
I get this when installing on a Windows 7 32 bit machine.

> node lib/install.js

  ‼ spawn ENOENT
  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installe
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
imagemin-pngquant@4.0.0 node_modules\imagemin-pngquant
├── is-png@1.0.0
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
└── pngquant-bin@2.0.3 (logalot@2.1.0, bin-wrapper@2.1.3, bin-build@2.1.0)

Cheers,
Dave

**Comment by woutrbe** [comment]
Any update on this?

**Comment by kevva** [comment]
Not sure if the binary works on Windows x64 machines.
